# Generated by Django 4.2.6 on 2024-02-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_semester_info_uni_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester_info',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
    ]
