# Generated by Django 4.2.6 on 2024-02-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_semester_info_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='semester_info',
            name='branch',
        ),
    ]
