# Generated by Django 4.2.6 on 2024-02-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_course_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.CharField(choices=[('1', 'A'), ('B', 'B'), ('C', 'C')], default='1', max_length=50)),
            ],
        ),
    ]
