# Generated by Django 4.2.6 on 2024-02-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_info',
            name='groups',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
        migrations.AlterField(
            model_name='course_info',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.branch'),
        ),
    ]
