# Generated by Django 4.2.6 on 2024-02-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_course_info_groups_alter_course_info_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='Group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('E', 'E'), ('F', 'F')], default='', max_length=50),
        ),
    ]
