# Generated by Django 4.2.6 on 2024-02-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_group_course_name_alter_group_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='course_name',
            new_name='course_name1',
        ),
        migrations.AddField(
            model_name='group',
            name='course_name2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='course_name3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='course_name4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
