# Generated by Django 4.2.6 on 2024-02-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_semester_remove_semester_info_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester_info',
            name='sem',
        ),
    ]
