# Generated by Django 4.2.6 on 2024-02-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_semester_info_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.branch'),
        ),
        migrations.AddField(
            model_name='group',
            name='semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.semester'),
        ),
    ]
