# Generated by Django 4.2.6 on 2024-02-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_group_department_group_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(default=0)),
                ('branch', models.CharField(default='', max_length=100)),
                ('Group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('E', 'E'), ('F', 'F')], default='', max_length=50)),
                ('course_name1', models.CharField(default='', max_length=100)),
                ('course_name2', models.CharField(default='', max_length=100)),
                ('course_name3', models.CharField(default='', max_length=100)),
                ('course_name4', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course_info',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='course_info',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='group',
            name='department',
        ),
        migrations.RemoveField(
            model_name='group',
            name='semester',
        ),
        migrations.AddField(
            model_name='semester_info',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='semester_info',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='course_info',
        ),
        migrations.DeleteModel(
            name='group',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
