# Generated by Django 4.2.6 on 2024-02-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester_info',
            name='rolls',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.roll_no'),
        ),
        migrations.AlterField(
            model_name='roll_no',
            name='roll',
            field=models.IntegerField(default=0),
        ),
    ]
