# Generated by Django 4.2.6 on 2024-02-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_semester_info_rolls_alter_roll_no_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='semester_info',
            name='rolls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rollno'),
        ),
        migrations.DeleteModel(
            name='roll_no',
        ),
    ]
