# Generated by Django 4.2.6 on 2024-02-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rollno_alter_semester_info_rolls_delete_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_info',
            name='rolls',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.rollno'),
        ),
    ]
