# Generated by Django 4.2.6 on 2024-02-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_semester_info_rolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester_info',
            name='rolls',
        ),
    ]
