# Generated by Django 4.2.6 on 2024-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_rollno_roll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RollNo',
        ),
        migrations.AddField(
            model_name='semester_info',
            name='roll',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='Group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default=None, max_length=50),
        ),
    ]
